# Generated by Django 5.1.5 on 2025-02-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('feuer', models.CharField(max_length=50)),
                ('wasser', models.CharField(max_length=50)),
                ('eis', models.CharField(max_length=50)),
                ('blitz', models.CharField(max_length=50)),
                ('gift', models.CharField(max_length=50)),
                ('lähmung', models.CharField(max_length=50)),
                ('explosion', models.CharField(max_length=50)),
                ('schlaf', models.CharField(max_length=50)),
            ],
        ),
    ]
